export const RESET_STATE = "CATEGORY_RESET_STATE";

export const REQUEST_LOADING = "CATEGORY_REQUEST_LOADING";
export const REQUEST_SUCCESS = "CATEGORY_REQUEST_SUCCESS";
export const REQUEST_FAILED = "CATEGORY_REQUEST_FAILED";
