export const RESET_STATE = "IMAGES_RESET_STATE";

export const REQUEST_LOADING = "IMAGES_REQUEST_LOADING";
export const REQUEST_SUCCESS = "IMAGES_REQUEST_SUCCESS";
export const REQUEST_FAILED = "IMAGES_REQUEST_FAILED";
